#!/usr/bin/env python3
"""Generate .github/CODEOWNERS from Riksdagen's departement-SFS mapping.

Queries the Riksdagen API for departement assignments and generates
CODEOWNERS entries mapping file paths to GitHub teams.

Usage:
    python scripts/import/generate_codeowners.py > .github/CODEOWNERS
"""

import os
import sys
from pathlib import Path

import requests
import yaml

RIKSDAGEN_API_BASE = os.environ.get(
    "RIKSDAGEN_API_BASE", "https://data.riksdagen.se"
)
USER_AGENT = os.environ.get(
    "USER_AGENT", "Lagläget/1.0 (github.com/lardinator/lagl-get)"
)
REPO_ROOT = Path(__file__).resolve().parent.parent.parent

# Map Swedish department names to GitHub team slugs
DEPARTEMENT_TEAMS = {
    "Justitiedepartementet": "justitiedepartementet",
    "Finansdepartementet": "finansdepartementet",
    "Utbildningsdepartementet": "utbildningsdepartementet",
    "Socialdepartementet": "socialdepartementet",
    "Klimat- och näringslivsdepartementet": "klimat-och-naringsdepartementet",
    "Försvarsdepartementet": "forsvarsdepartementet",
    "Utrikesdepartementet": "utrikesdepartementet",
    "Kulturdepartementet": "kulturdepartementet",
    "Arbetsmarknadsdepartementet": "arbetsmarknadsdepartementet",
    "Statsrådsberedningen": "statsradsberedningen",
}


def scan_law_files() -> list[dict]:
    """Scan all law files and extract SFS number + departement."""
    entries = []
    for dir_name in ["lagar", "förordningar", "grundlagar"]:
        dir_path = REPO_ROOT / dir_name
        if not dir_path.is_dir():
            continue
        for md_file in sorted(dir_path.rglob("*.md")):
            content = md_file.read_text(encoding="utf-8")
            if not content.startswith("---"):
                continue
            parts = content.split("---", 2)
            if len(parts) < 3:
                continue
            try:
                fm = yaml.safe_load(parts[1])
                entries.append({
                    "path": str(md_file.relative_to(REPO_ROOT)),
                    "sfs": fm.get("sfs", ""),
                    "titel": fm.get("titel", ""),
                    "departement": fm.get("departement", ""),
                })
            except yaml.YAMLError:
                continue
    return entries


def generate_codeowners(entries: list[dict]) -> str:
    """Generate CODEOWNERS content from law file entries."""
    lines = [
        "# Lagläget — CODEOWNERS",
        "# Auto-generated by scripts/import/generate_codeowners.py",
        "#",
        "# Departements own their SFS ranges.",
        "",
        "# Grundlagarna — requires KU review",
        "/grundlagar/ @riksdaget/statsradsberedningen @riksdaget/ku",
        "",
    ]

    for entry in entries:
        dept = entry["departement"]
        team_slug = DEPARTEMENT_TEAMS.get(dept)
        if not team_slug:
            continue
        path = entry["path"]
        titel = entry.get("titel", "")
        comment = f"  # {titel}" if titel else ""
        lines.append(f"/{path} @riksdaget/{team_slug}{comment}")

    lines.append("")
    lines.append("# Förordningar — Statsrådsberedningen")
    lines.append("/förordningar/ @riksdaget/statsradsberedningen")
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    entries = scan_law_files()
    print(generate_codeowners(entries))


if __name__ == "__main__":
    main()
